In [5]:
#A normal python list:

a = [[123,12,123,12.33],[],[]]
a

[[123, 12, 123, 12.33], [], []]

In [2]:
import numpy
n = numpy.arange(27)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [3]:
#Numpy unlike list is an array
#Representing 2-D Array

n.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [4]:
#Representing 3-D Array
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [10]:
#Creating numpy array from this python list:

m = numpy.asarray([[123,12,123,12.33],[],[]])
m

C:\Users\User\AppData\Local\Temp\ipykernel_28164\2400023488.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  m = numpy.asarray([[123,12,123,12.33],[],[]])


array([list([123, 12, 123, 12.33]), list([]), list([])], dtype=object)