In [2]:
import pandas
import numpy
import cv2
import os
os.listdir()


['.ipynb_checkpoints',
 '121_What is Numpy..ipynb',
 '123_Converting Images to Numpy Array.ipynb',
 'smallgray.png']

In [4]:
#Creating Numpy array using Images.

image = cv2.imread("smallgray.png",0)

# 0 means you want to display the image in grayscale
# 1 means you want to display the image in BGR-blue green red.

image


array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [6]:
image1 = cv2.imread("smallgray.png",1)
print(image1)


[[[187 187 187]
  [158 158 158]
  [104 104 104]
  [121 121 121]
  [143 143 143]]

 [[198 198 198]
  [125 125 125]
  [255 255 255]
  [255 255 255]
  [147 147 147]]

 [[209 209 209]
  [134 134 134]
  [255 255 255]
  [ 97  97  97]
  [182 182 182]]]


In [8]:
#Creating images off of Numpy Arrays

cv2.imwrite("newsmallgray.png",image)

True

In [ ]:
#True means an image has been created.