In [1]:
import os
os.listdir()

['.ipynb_checkpoints',
 '121_What is Numpy..ipynb',
 '123_Converting Images to Numpy Array.ipynb',
 '124_Indexing,Slicing and Iterating Numpy Arrays..ipynb',
 'newsmallgray.png',
 'smallgray.png']

In [2]:
import pandas
import numpy
import cv2


In [3]:
image = cv2.imread("smallgray.png",0)

In [4]:
image

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [5]:
#Indexing and Slicing in grayscale

image[0:2,2:4]




array([[104, 121],
       [255, 255]], dtype=uint8)

In [6]:
image[2,4]


182

In [7]:
#Iterating in Numpy Array

In [8]:
#Printing rows of the numpy arrays

for i in image:
    print (i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [9]:
#Printing Columns of numpy Arrays.(t = transpose)

for i in image.T:
    print (i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [10]:
#Printing one by one in numpy arrays.

for i in image.flat:
    print(i)
    

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182
