In [1]:
import os
os.listdir()


['.ipynb_checkpoints',
 '121_What is Numpy..ipynb',
 '123_Converting Images to Numpy Array.ipynb',
 '124_Indexing,Slicing and Iterating Numpy Arrays..ipynb',
 '125-Stacking and Splitting Numpy Arrays.ipynb',
 'newsmallgray.png',
 'smallgray.png']

In [2]:
import pandas
import numpy
import cv2


In [3]:
image = cv2.imread("smallgray.png",0)

In [4]:
image

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [13]:
#Stacking Numpy Arrays:

#Horizontal Stacking :

imageh = numpy.hstack((image,image,image))                                           #hstack means horizontal stack which only takes one argument.So you need to make a topple.
print(imageh)



[[187 158 104 121 143 187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182 209 134 255  97 182]]


In [14]:
#Vertical Stacking : 

imagev = numpy.vstack((image,image,image))
print (imagev)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [10]:
# Splitting Numpy Arrays:


In [17]:
# Horizontal Splitting :

imagesh = numpy.hsplit(imagev,5)
imagesh                                                   #Array split into 5 subsequent arrays through horizontal axis



[array([[187],
        [198],
        [209],
        [187],
        [198],
        [209],
        [187],
        [198],
        [209]], dtype=uint8),
 array([[158],
        [125],
        [134],
        [158],
        [125],
        [134],
        [158],
        [125],
        [134]], dtype=uint8),
 array([[104],
        [255],
        [255],
        [104],
        [255],
        [255],
        [104],
        [255],
        [255]], dtype=uint8),
 array([[121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97]], dtype=uint8),
 array([[143],
        [147],
        [182],
        [143],
        [147],
        [182],
        [143],
        [147],
        [182]], dtype=uint8)]

In [18]:
# Vertical Splitting

imagesv = numpy.vsplit(imagev,3)
imagesv                                            #Array split into 3 subsequent arrays through vertical axis

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]

In [19]:
 type(imagesv)

list

In [21]:
imagesv[0]                                         #Gives the first Array


array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)