In [6]:
import os
os.listdir()

['.ipynb_checkpoints',
 '149.Loading,Creating,Resizing and Displaying Images.ipynb',
 '150. Resizing Exercise.ipynb',
 '151. Solution to exercise of resizing images.ipynb',
 '152.Detecting Faces in Python.ipynb',
 '154.Capturing video with python.ipynb',
 'Face tracking image.jpg',
 'galaxy.jpg',
 'Galaxy_Resized.jpg',
 'haarcascade_frontalface_default.xml',
 'kangaroos-rain-australia_71370_990x742.jpg',
 'Lighthouse.jpg',
 'Moon sinking, sun rising.jpg',
 'news.jpg',
 'photo.jpg']

In [9]:
import cv2,time
#DISPLAYS ONLY THE FIRST FRAME:

#Switching webcame to take video : 

video = cv2.VideoCapture(0)                         #Switches on the web camera. 0 for builtin camera and 1 for external camera
check,frame = video.read()                          #Captures Each frame and also checks whether video is read or not 
print(check)                                        #Prints whether true or false with respect to if video is read or not
print(frame)                                        #Print Frame in the form of a numpy array

#Converting frame captured to grayscale (Optional):

gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)       #Converts the BGR frame into a grayscale
#time.sleep(3)                                      #Makes the control of python program sleep for 3 seconds

#Displaying the captured frame in an external window:

cv2.imshow("Capturing",gray)                        #Shows the converted gray scale image in another window
cv2.waitKey(0)                                      #Transfers control to next statement when a key is pressed form the window
video.release()                                     #The webcame turns off and video is released
cv2.destroyAllWindows()                             #Exteral window gets destroyed






 

True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [189 163 157]
  [189 163 157]
  [189 163 157]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [189 163 157]
  [189 163 157]
  [189 163 157]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [189 163 157]
  [188 163 157]
  [188 163 157]]

 ...

 [[ 79  79  96]
  [ 78  78  96]
  [ 78  77  96]
  ...
  [ 30  29  39]
  [ 34  30  42]
  [ 36  31  43]]

 [[ 80  80  97]
  [ 80  80  98]
  [ 79  78  97]
  ...
  [ 25  22  37]
  [ 29  23  41]
  [ 31  24  42]]

 [[ 82  82  99]
  [ 81  81  99]
  [ 79  78  97]
  ...
  [ 22  19  36]
  [ 26  19  39]
  [ 28  20  41]]]


In [13]:
#Displaying an entire video :

video = cv2.VideoCapture(0)                         #Switches on the web camera. 0 for builtin camera and 1 for external camera

frame_number = 0

while True:                                                   #Iterating per milli second to display a video
    frame_number = frame_number + 1
    check,frame = video.read()                                #Captures Each frame and also checks whether video is read or not 
    print(check)                                              #Prints whether true or false with respect to if video is read or not
    print(frame)                                              #Print Frame in the form of a numpy array

    #Converting frame captured to grayscale (Optional):

    #gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)             #Converts the BGR frame into a grayscale
    #time.sleep(3)                                            #Makes the control of python program sleep for 3 seconds

    #Displaying the captured frame in an external window:

    cv2.imshow("Capturing",frame)                              #Shows the converted gray scale image in another window
    key = cv2.waitKey(1)                                      #Transfers control to next loop unless q is pressed where it breaks from loop
    if key==ord('q'):
        break

video.release()                                               #The webcame turns off and video is released
cv2.destroyAllWindows()                                       #Exteral window gets destroyed
print(frame_number)
    




True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [176 158 145]
  [177 159 146]
  [177 159 146]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [177 159 146]
  [177 159 146]
  [177 159 146]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [177 159 147]
  [177 159 147]
  [177 159 147]]

 ...

 [[ 41  40  43]
  [ 43  42  45]
  [ 43  43  46]
  ...
  [ 43  43  43]
  [ 44  44  44]
  [ 44  44  44]]

 [[ 36  39  46]
  [ 36  41  47]
  [ 37  43  48]
  ...
  [ 45  46  44]
  [ 46  47  45]
  [ 46  47  45]]

 [[ 33  39  48]
  [ 33  40  48]
  [ 34  43  50]
  ...
  [ 46  47  44]
  [ 47  48  45]
  [ 48  49  46]]]
True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [193 163 158]
  [195 166 161]
  [196 167 162]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [191 162 157]
  [194 165 160]
  [195 166 161]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [188 162 156]
  [191 164 158]
  [192 165 159]]

 ...

 [[ 49  42  37]
  [ 49  42  39]
  [ 48  43

True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [169 162 160]
  [170 162 163]
  [171 163 164]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [169 160 159]
  [170 162 163]
  [171 162 164]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [171 160 159]
  [171 161 162]
  [171 161 163]]

 ...

 [[ 23  31  51]
  [ 24  31  51]
  [ 24  31  51]
  ...
  [ 40  40  40]
  [ 38  39  39]
  [ 36  37  37]]

 [[ 28  29  56]
  [ 27  27  54]
  [ 26  26  53]
  ...
  [ 43  36  37]
  [ 41  35  36]
  [ 39  33  34]]

 [[ 30  28  58]
  [ 29  26  56]
  [ 28  23  54]
  ...
  [ 42  31  33]
  [ 39  29  31]
  [ 37  27  29]]]
True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [171 161 167]
  [171 160 170]
  [170 159 171]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [172 162 165]
  [172 160 168]
  [172 160 170]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [173 162 161]
  [174 160 164]
  [174 159 166]]

 ...

 [[ 28  37  37]
  [ 33  42  42]
  [ 37  45

True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [231 217 205]
  [233 220 206]
  [234 221 206]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [232 217 207]
  [234 219 207]
  [235 220 207]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [233 216 209]
  [235 218 209]
  [235 218 208]]

 ...

 [[ 58  60  59]
  [ 57  61  59]
  [ 57  66  63]
  ...
  [ 74  65  66]
  [ 73  66  67]
  [ 73  67  68]]

 [[ 58  56  56]
  [ 59  59  59]
  [ 60  65  63]
  ...
  [ 80  62  65]
  [ 81  65  66]
  [ 82  67  68]]

 [[ 58  53  54]
  [ 61  59  59]
  [ 63  65  65]
  ...
  [ 84  63  66]
  [ 86  65  67]
  [ 89  68  69]]]
True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [231 217 205]
  [233 220 206]
  [234 221 206]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [232 217 207]
  [234 219 207]
  [235 220 207]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [233 216 209]
  [235 218 209]
  [235 218 208]]

 ...

 [[ 58  60  59]
  [ 57  61  59]
  [ 57  66

True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [230 215 215]
  [231 214 217]
  [232 214 217]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [230 215 215]
  [231 215 217]
  [231 214 217]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [229 215 216]
  [230 215 217]
  [230 214 217]]

 ...

 [[ 74  85  82]
  [ 68  79  76]
  [ 60  71  68]
  ...
  [ 68  68  69]
  [ 68  67  70]
  [ 69  68  71]]

 [[ 73  83  81]
  [ 67  76  74]
  [ 60  69  66]
  ...
  [ 67  67  68]
  [ 68  67  69]
  [ 68  67  70]]

 [[ 74  82  81]
  [ 66  74  73]
  [ 58  67  64]
  ...
  [ 67  67  67]
  [ 68  67  69]
  [ 68  67  70]]]
True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [230 215 215]
  [231 214 217]
  [232 214 217]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [230 215 215]
  [231 215 217]
  [231 214 217]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [229 215 216]
  [230 215 217]
  [230 214 217]]

 ...

 [[ 74  85  82]
  [ 68  79  76]
  [ 60  71

True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [233 221 209]
  [233 220 211]
  [234 221 212]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [233 222 209]
  [233 221 210]
  [233 221 210]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [233 221 207]
  [233 222 208]
  [233 222 208]]

 ...

 [[ 91  86  97]
  [ 87  82  93]
  [ 79  76  87]
  ...
  [ 75  64  66]
  [ 78  64  66]
  [ 80  64  65]]

 [[ 84  88 102]
  [ 79  83  97]
  [ 72  76  90]
  ...
  [ 79  64  66]
  [ 84  63  65]
  [ 87  63  65]]

 [[ 77  86 102]
  [ 72  81  97]
  [ 67  75  91]
  ...
  [ 81  63  66]
  [ 87  63  65]
  [ 91  62  64]]]
True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [233 221 209]
  [233 220 211]
  [234 221 212]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [233 222 209]
  [233 221 210]
  [233 221 210]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [233 221 207]
  [233 222 208]
  [233 222 208]]

 ...

 [[ 91  86  97]
  [ 87  82  93]
  [ 79  76

True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [234 214 214]
  [235 213 215]
  [236 213 215]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [233 213 213]
  [234 212 213]
  [235 212 214]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [233 213 212]
  [235 212 213]
  [235 212 213]]

 ...

 [[ 59  66  72]
  [ 57  64  70]
  [ 56  63  69]
  ...
  [ 78  71  68]
  [ 76  70  68]
  [ 74  69  67]]

 [[ 54  58  73]
  [ 54  59  74]
  [ 54  61  74]
  ...
  [ 77  71  66]
  [ 76  70  67]
  [ 75  70  68]]

 [[ 49  51  71]
  [ 51  55  74]
  [ 52  59  76]
  ...
  [ 77  71  65]
  [ 76  71  67]
  [ 75  70  67]]]
True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [234 214 214]
  [235 213 215]
  [236 213 215]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [233 213 213]
  [234 212 213]
  [235 212 214]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [233 213 212]
  [235 212 213]
  [235 212 213]]

 ...

 [[ 59  66  72]
  [ 57  64  70]
  [ 56  63

True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [235 217 210]
  [234 216 209]
  [233 215 208]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [235 217 209]
  [234 216 209]
  [233 215 208]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [235 218 209]
  [234 217 208]
  [233 216 207]]

 ...

 [[ 41  59  69]
  [ 47  65  73]
  [ 53  71  78]
  ...
  [ 69  70  61]
  [ 67  69  60]
  [ 67  69  60]]

 [[ 38  62  68]
  [ 45  68  73]
  [ 52  74  78]
  ...
  [ 66  69  60]
  [ 64  68  59]
  [ 64  68  59]]

 [[ 34  61  64]
  [ 40  66  69]
  [ 49  73  75]
  ...
  [ 64  68  59]
  [ 63  68  59]
  [ 63  68  59]]]
True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [233 218 207]
  [231 216 207]
  [231 216 207]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [232 218 207]
  [231 216 207]
  [231 216 207]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [231 218 208]
  [231 218 208]
  [231 218 207]]

 ...

 [[ 49  45  59]
  [ 51  48  61]
  [ 52  51

True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [227 218 212]
  [226 216 215]
  [225 215 215]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [227 217 212]
  [226 216 215]
  [226 216 217]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [227 217 214]
  [226 216 216]
  [225 215 217]]

 ...

 [[ 62  62  96]
  [ 64  63  96]
  [ 65  65  95]
  ...
  [ 69  69  52]
  [ 71  70  49]
  [ 72  71  47]]

 [[ 51  62  93]
  [ 54  64  95]
  [ 55  65  95]
  ...
  [ 68  68  52]
  [ 72  69  50]
  [ 73  70  49]]

 [[ 43  60  90]
  [ 47  63  92]
  [ 50  65  94]
  ...
  [ 67  66  52]
  [ 71  68  50]
  [ 73  68  49]]]
True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [227 218 212]
  [226 216 215]
  [225 215 215]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [227 217 212]
  [226 216 215]
  [226 216 217]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [227 217 214]
  [226 216 216]
  [225 215 217]]

 ...

 [[ 62  62  96]
  [ 64  63  96]
  [ 65  65

True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [235 213 217]
  [234 212 217]
  [234 212 218]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [233 213 216]
  [233 212 217]
  [233 212 217]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [232 214 217]
  [231 213 216]
  [231 213 216]]

 ...

 [[ 47  55  78]
  [ 48  56  76]
  [ 54  61  77]
  ...
  [ 72  70  70]
  [ 70  69  69]
  [ 69  69  69]]

 [[ 50  55  67]
  [ 52  56  67]
  [ 59  63  71]
  ...
  [ 71  71  72]
  [ 70  71  71]
  [ 69  71  71]]

 [[ 56  59  64]
  [ 57  60  64]
  [ 63  66  68]
  ...
  [ 70  72  74]
  [ 70  72  72]
  [ 70  73  72]]]
True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [235 213 217]
  [234 212 217]
  [234 212 218]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [233 213 216]
  [233 212 217]
  [233 212 217]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [232 214 217]
  [231 213 216]
  [231 213 216]]

 ...

 [[ 47  55  78]
  [ 48  56  76]
  [ 54  61

True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [237 215 214]
  [239 217 216]
  [240 218 217]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [237 214 215]
  [239 216 217]
  [239 217 216]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [237 214 216]
  [238 215 216]
  [239 216 217]]

 ...

 [[120 128 148]
  [121 128 148]
  [124 128 150]
  ...
  [ 28  27  37]
  [ 22  25  37]
  [ 18  23  35]]

 [[120 126 152]
  [122 127 152]
  [125 128 153]
  ...
  [ 23  26  35]
  [ 16  23  35]
  [ 14  23  37]]

 [[121 126 155]
  [122 126 154]
  [125 127 154]
  ...
  [ 18  23  31]
  [ 12  22  33]
  [  9  21  35]]]
True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [237 215 214]
  [239 217 216]
  [240 218 217]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [237 214 215]
  [239 216 217]
  [239 217 216]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [237 214 216]
  [238 215 216]
  [239 216 217]]

 ...

 [[120 128 148]
  [121 128 148]
  [124 128

True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [230 216 214]
  [228 212 216]
  [226 211 216]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [230 215 215]
  [229 213 217]
  [226 210 216]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [230 215 217]
  [229 213 218]
  [227 211 218]]

 ...

 [[132 123 147]
  [131 123 148]
  [130 122 149]
  ...
  [120 106 115]
  [127 114 120]
  [136 124 130]]

 [[130 121 151]
  [129 120 150]
  [128 120 151]
  ...
  [119 105 120]
  [118 106 119]
  [117 106 118]]

 [[128 119 152]
  [128 119 152]
  [127 119 152]
  ...
  [111  97 115]
  [115 104 120]
  [118 107 122]]]
True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [230 216 214]
  [228 212 216]
  [226 211 216]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [230 215 215]
  [229 213 217]
  [226 210 216]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [230 215 217]
  [229 213 218]
  [227 211 218]]

 ...

 [[132 123 147]
  [131 123 148]
  [130 122

True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [233 216 215]
  [231 215 215]
  [231 215 216]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [232 215 215]
  [231 215 215]
  [231 215 216]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [232 215 216]
  [231 215 216]
  [229 214 215]]

 ...

 [[125 129 151]
  [123 129 148]
  [119 128 144]
  ...
  [113 115 120]
  [116 115 118]
  [114 113 113]]

 [[123 130 150]
  [121 130 147]
  [118 130 144]
  ...
  [105 104 120]
  [109 106 119]
  [118 113 126]]

 [[123 130 149]
  [121 131 148]
  [118 132 144]
  ...
  [ 97  94 115]
  [100  94 114]
  [113 105 125]]]
True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [232 216 216]
  [233 217 217]
  [234 218 218]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [233 216 217]
  [234 216 219]
  [234 216 219]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [235 214 219]
  [235 214 220]
  [236 215 221]]

 ...

 [[130 122 146]
  [130 123 147]
  [129 123

True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [231 219 214]
  [233 219 214]
  [233 219 213]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [231 218 213]
  [232 218 212]
  [233 218 212]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [233 218 212]
  [233 218 212]
  [234 218 212]]

 ...

 [[125 131 147]
  [123 130 146]
  [120 129 146]
  ...
  [104 104 115]
  [114 116 126]
  [115 119 128]]

 [[121 132 145]
  [120 133 145]
  [118 132 144]
  ...
  [103 101 113]
  [113 114 124]
  [111 114 122]]

 [[117 132 143]
  [118 134 144]
  [118 135 145]
  ...
  [ 98  95 107]
  [107 108 116]
  [109 111 118]]]
True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [231 219 214]
  [233 219 214]
  [233 219 213]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [231 218 213]
  [232 218 212]
  [233 218 212]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [233 218 212]
  [233 218 212]
  [234 218 212]]

 ...

 [[125 131 147]
  [123 130 146]
  [120 129

True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [240 214 210]
  [239 215 209]
  [239 215 209]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [239 215 210]
  [239 215 209]
  [239 215 209]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [239 215 209]
  [238 215 209]
  [238 215 209]]

 ...

 [[118 128 155]
  [120 129 156]
  [123 131 155]
  ...
  [118  99  68]
  [121 101  74]
  [124 103  78]]

 [[118 130 154]
  [119 130 153]
  [123 131 154]
  ...
  [117 101  65]
  [118 100  70]
  [120 101  74]]

 [[117 131 152]
  [119 131 152]
  [123 132 152]
  ...
  [116 100  63]
  [117 100  68]
  [116  98  69]]]
True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [240 214 210]
  [239 215 209]
  [239 215 209]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [239 215 210]
  [239 215 209]
  [239 215 209]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [239 215 209]
  [238 215 209]
  [238 215 209]]

 ...

 [[118 128 155]
  [120 129 156]
  [123 131

True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [231 214 217]
  [231 215 216]
  [232 216 217]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [230 213 216]
  [231 215 216]
  [231 215 215]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [229 213 214]
  [230 214 214]
  [230 214 214]]

 ...

 [[128 125 155]
  [127 125 155]
  [126 126 154]
  ...
  [126  96  97]
  [126  95  97]
  [134 101 104]]

 [[121 127 150]
  [121 127 150]
  [120 127 149]
  ...
  [123  96  96]
  [123  92  94]
  [131  98 102]]

 [[118 129 148]
  [118 129 147]
  [118 129 147]
  ...
  [122  96  95]
  [123  93  95]
  [131  99 103]]]
True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [231 214 217]
  [231 215 216]
  [232 216 217]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [230 213 216]
  [231 215 216]
  [231 215 215]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [229 213 214]
  [230 214 214]
  [230 214 214]]

 ...

 [[128 125 155]
  [127 125 155]
  [126 126

True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [235 214 219]
  [236 215 220]
  [238 216 222]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [235 214 219]
  [237 215 220]
  [237 215 221]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [235 214 219]
  [236 214 219]
  [236 214 219]]

 ...

 [[129 130 141]
  [129 128 142]
  [130 126 145]
  ...
  [115  97  90]
  [119 100  94]
  [119  99  94]]

 [[128 129 139]
  [129 128 141]
  [131 126 144]
  ...
  [114  98  84]
  [117 101  85]
  [118 101  85]]

 [[129 130 140]
  [130 129 142]
  [133 127 145]
  ...
  [115 100  82]
  [117 103  82]
  [118 103  81]]]
True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [234 213 209]
  [235 212 211]
  [235 210 211]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [235 214 210]
  [235 212 211]
  [235 211 212]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [234 214 210]
  [235 213 212]
  [236 212 213]]

 ...

 [[128 124 150]
  [127 123 151]
  [127 123

True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [238 215 210]
  [239 216 211]
  [239 216 211]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [238 215 212]
  [238 215 212]
  [238 215 212]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [236 215 215]
  [237 214 215]
  [238 215 216]]

 ...

 [[128 133 132]
  [129 133 132]
  [130 132 133]
  ...
  [110  90  77]
  [113  90  81]
  [115  92  84]]

 [[127 130 135]
  [128 130 135]
  [130 130 137]
  ...
  [113  91  73]
  [116  91  77]
  [118  93  81]]

 [[128 130 138]
  [129 129 138]
  [129 129 139]
  ...
  [115  91  72]
  [117  91  75]
  [119  92  78]]]
True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [238 215 210]
  [239 216 211]
  [239 216 211]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [238 215 212]
  [238 215 212]
  [238 215 212]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [236 215 215]
  [237 214 215]
  [238 215 216]]

 ...

 [[128 133 132]
  [129 133 132]
  [130 132

True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [229 214 219]
  [228 214 219]
  [228 215 219]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [229 214 219]
  [228 214 219]
  [228 214 219]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [229 214 218]
  [229 214 219]
  [229 214 219]]

 ...

 [[123 128 140]
  [124 128 140]
  [125 127 141]
  ...
  [106  94  89]
  [109  92  92]
  [112  92  94]]

 [[130 123 144]
  [129 123 144]
  [128 124 143]
  ...
  [106  96  86]
  [110  94  89]
  [112  92  90]]

 [[133 120 146]
  [132 120 145]
  [131 122 144]
  ...
  [107  97  84]
  [110  93  86]
  [112  92  88]]]
True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [229 214 219]
  [228 214 219]
  [228 215 219]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [229 214 219]
  [228 214 219]
  [228 214 219]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [229 214 218]
  [229 214 219]
  [229 214 219]]

 ...

 [[123 128 140]
  [124 128 140]
  [125 127

True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [232 215 211]
  [232 216 211]
  [232 216 210]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [232 216 211]
  [232 216 210]
  [232 216 210]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [232 216 210]
  [232 216 210]
  [232 216 210]]

 ...

 [[136 140 143]
  [136 139 143]
  [136 137 144]
  ...
  [100  90  80]
  [101  93  80]
  [101  93  80]]

 [[137 141 139]
  [136 141 140]
  [137 140 142]
  ...
  [ 99  90  80]
  [ 99  92  79]
  [ 99  94  80]]

 [[136 141 136]
  [135 141 137]
  [136 141 140]
  ...
  [100  92  83]
  [100  94  82]
  [ 99  95  81]]]
True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [232 215 211]
  [232 216 211]
  [232 216 210]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [232 216 211]
  [232 216 210]
  [232 216 210]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [232 216 210]
  [232 216 210]
  [232 216 210]]

 ...

 [[136 140 143]
  [136 139 143]
  [136 137

True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [233 215 214]
  [233 216 214]
  [233 216 214]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [233 215 215]
  [233 215 215]
  [233 215 215]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [232 215 216]
  [233 214 216]
  [233 214 216]]

 ...

 [[129 125 157]
  [129 124 156]
  [130 124 155]
  ...
  [107  93  79]
  [109  95  80]
  [109  95  80]]

 [[124 124 157]
  [126 124 156]
  [127 124 154]
  ...
  [102  91  78]
  [103  93  80]
  [105  95  82]]

 [[120 123 155]
  [122 123 154]
  [126 124 154]
  ...
  [ 99  90  77]
  [ 99  91  78]
  [103  95  83]]]
True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [233 215 214]
  [233 216 214]
  [233 216 214]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [233 215 215]
  [233 215 215]
  [233 215 215]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [232 215 216]
  [233 214 216]
  [233 214 216]]

 ...

 [[129 125 157]
  [129 124 156]
  [130 124

True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [239 215 207]
  [239 215 205]
  [240 217 206]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [238 215 207]
  [239 216 207]
  [239 217 206]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [237 216 209]
  [237 217 207]
  [238 218 207]]

 ...

 [[119 125 155]
  [120 126 156]
  [120 124 155]
  ...
  [118  93  76]
  [120  97  75]
  [123 100  76]]

 [[120 122 156]
  [122 123 156]
  [123 123 156]
  ...
  [115  95  78]
  [117  97  76]
  [118  98  76]]

 [[121 121 156]
  [122 122 156]
  [124 123 156]
  ...
  [114  96  79]
  [115  97  77]
  [117  98  77]]]
True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [239 215 207]
  [239 215 205]
  [240 217 206]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [238 215 207]
  [239 216 207]
  [239 217 206]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [237 216 209]
  [237 217 207]
  [238 218 207]]

 ...

 [[119 125 155]
  [120 126 156]
  [120 124

True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [237 216 205]
  [238 219 202]
  [238 220 201]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [237 217 206]
  [237 219 203]
  [237 219 202]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [236 218 209]
  [236 219 206]
  [236 220 205]]

 ...

 [[130 120 147]
  [130 121 148]
  [131 123 151]
  ...
  [100  92  83]
  [101  94  82]
  [103  96  82]]

 [[131 121 150]
  [130 121 151]
  [129 122 152]
  ...
  [100  92  78]
  [101  94  78]
  [101  96  78]]

 [[131 122 152]
  [130 122 152]
  [127 122 153]
  ...
  [101  93  76]
  [100  94  75]
  [100  96  75]]]
True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [237 216 205]
  [238 219 202]
  [238 220 201]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [237 217 206]
  [237 219 203]
  [237 219 202]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [236 218 209]
  [236 219 206]
  [236 220 205]]

 ...

 [[130 120 147]
  [130 121 148]
  [131 123

True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [232 216 217]
  [233 216 216]
  [234 216 215]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [234 217 217]
  [235 217 216]
  [236 217 216]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [235 216 215]
  [237 218 215]
  [238 218 214]]

 ...

 [[128 128 155]
  [129 128 154]
  [128 128 152]
  ...
  [120  95  82]
  [120  97  82]
  [120  99  82]]

 [[130 127 155]
  [129 126 154]
  [129 127 153]
  ...
  [119  93  81]
  [119  94  80]
  [119  95  80]]

 [[131 127 156]
  [130 126 154]
  [130 127 154]
  ...
  [120  94  82]
  [120  94  81]
  [120  94  80]]]
True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [232 216 217]
  [233 216 216]
  [234 216 215]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [234 217 217]
  [235 217 216]
  [236 217 216]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [235 216 215]
  [237 218 215]
  [238 218 214]]

 ...

 [[128 128 155]
  [129 128 154]
  [128 128

True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [233 216 214]
  [232 216 213]
  [231 217 213]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [232 216 214]
  [231 216 213]
  [231 217 213]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [230 215 212]
  [229 216 212]
  [230 217 213]]

 ...

 [[114 129 149]
  [113 127 149]
  [114 127 149]
  ...
  [112  92  87]
  [115  92  87]
  [117  93  88]]

 [[114 128 147]
  [113 126 147]
  [115 126 148]
  ...
  [112  91  79]
  [116  92  79]
  [118  93  80]]

 [[114 128 147]
  [114 126 146]
  [115 125 146]
  ...
  [112  91  74]
  [118  94  76]
  [122  97  78]]]
True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [233 216 214]
  [232 216 213]
  [231 217 213]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [232 216 214]
  [231 216 213]
  [231 217 213]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [230 215 212]
  [229 216 212]
  [230 217 213]]

 ...

 [[114 129 149]
  [113 127 149]
  [114 127

True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [232 214 218]
  [231 214 218]
  [231 214 219]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [233 215 219]
  [231 214 218]
  [231 213 219]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [233 215 219]
  [233 214 219]
  [233 214 220]]

 ...

 [[123 127 161]
  [123 128 160]
  [123 129 159]
  ...
  [104 100  89]
  [107 103  91]
  [109 105  93]]

 [[129 128 160]
  [129 130 161]
  [127 131 158]
  ...
  [103  98  92]
  [104 100  93]
  [104 101  94]]

 [[129 127 157]
  [128 127 156]
  [128 131 156]
  ...
  [103  98  94]
  [102  98  94]
  [102  98  94]]]
True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [232 214 218]
  [231 214 218]
  [231 214 219]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [233 215 219]
  [231 214 218]
  [231 213 219]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [233 215 219]
  [233 214 219]
  [233 214 220]]

 ...

 [[123 127 161]
  [123 128 160]
  [123 129

True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [232 220 213]
  [230 220 213]
  [230 221 214]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [232 219 213]
  [230 220 213]
  [229 220 213]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [230 218 213]
  [230 220 214]
  [229 220 214]]

 ...

 [[128 132 148]
  [128 131 146]
  [130 131 142]
  ...
  [106  85  80]
  [107  87  80]
  [108  88  81]]

 [[131 132 150]
  [131 131 148]
  [132 131 145]
  ...
  [103  85  85]
  [105  86  85]
  [107  87  86]]

 [[134 133 152]
  [134 133 150]
  [133 131 147]
  ...
  [101  84  87]
  [103  85  88]
  [106  87  90]]]
True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [232 220 213]
  [230 220 213]
  [230 221 214]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [232 219 213]
  [230 220 213]
  [229 220 213]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [230 218 213]
  [230 220 214]
  [229 220 214]]

 ...

 [[128 132 148]
  [128 131 146]
  [130 131

True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [232 216 219]
  [230 216 217]
  [230 217 217]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [233 217 218]
  [231 216 217]
  [231 216 216]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [234 217 217]
  [234 217 217]
  [233 216 215]]

 ...

 [[121 133 145]
  [120 133 145]
  [119 131 145]
  ...
  [104  93  85]
  [108  96  86]
  [110  97  86]]

 [[119 133 144]
  [119 133 145]
  [120 133 145]
  ...
  [103  90  88]
  [107  92  90]
  [109  93  91]]

 [[119 133 145]
  [119 133 145]
  [121 134 145]
  ...
  [100  87  88]
  [104  89  91]
  [108  90  93]]]
True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [232 216 219]
  [230 216 217]
  [230 217 217]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [233 217 218]
  [231 216 217]
  [231 216 216]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [234 217 217]
  [234 217 217]
  [233 216 215]]

 ...

 [[121 133 145]
  [120 133 145]
  [119 131

True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [239 212 212]
  [239 211 210]
  [239 211 210]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [239 212 211]
  [240 212 211]
  [241 212 210]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [239 213 211]
  [240 213 210]
  [242 214 210]]

 ...

 [[122 120 149]
  [121 118 147]
  [123 117 146]
  ...
  [106  95  84]
  [105  94  89]
  [106  96  93]]

 [[123 118 150]
  [120 114 146]
  [121 113 143]
  ...
  [105  98  81]
  [105  97  87]
  [105  97  90]]

 [[128 120 154]
  [124 116 149]
  [123 114 145]
  ...
  [105 101  80]
  [105 100  86]
  [104  98  88]]]
True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [233 215 214]
  [233 215 216]
  [233 214 217]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [233 216 214]
  [233 215 215]
  [233 215 215]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [234 216 212]
  [234 216 213]
  [234 216 213]]

 ...

 [[111 128 145]
  [112 128 144]
  [115 129

True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [235 216 205]
  [235 217 203]
  [235 218 203]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [235 216 206]
  [235 216 205]
  [235 217 204]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [236 215 210]
  [235 215 208]
  [235 215 207]]

 ...

 [[113 121 147]
  [114 122 149]
  [116 122 151]
  ...
  [108  94  73]
  [111  97  72]
  [113 100  73]]

 [[114 120 142]
  [115 121 144]
  [116 121 147]
  ...
  [104  97  72]
  [107  99  72]
  [108 100  71]]

 [[117 122 141]
  [118 122 143]
  [120 123 147]
  ...
  [103 100  73]
  [106 101  72]
  [108 103  72]]]
True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [235 216 205]
  [235 217 203]
  [235 218 203]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [235 216 206]
  [235 216 205]
  [235 217 204]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [236 215 210]
  [235 215 208]
  [235 215 207]]

 ...

 [[113 121 147]
  [114 122 149]
  [116 122

True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [229 215 206]
  [228 216 205]
  [228 216 205]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [230 216 208]
  [229 216 207]
  [228 216 206]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [231 215 209]
  [229 216 209]
  [229 216 208]]

 ...

 [[120 129 142]
  [119 129 143]
  [119 129 145]
  ...
  [108  89  89]
  [112  91  90]
  [114  92  91]]

 [[120 128 144]
  [119 128 144]
  [119 129 146]
  ...
  [108  89  91]
  [111  90  93]
  [113  91  94]]

 [[120 128 145]
  [119 128 145]
  [119 128 145]
  ...
  [108  90  93]
  [110  89  94]
  [111  89  94]]]
True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [229 215 206]
  [228 216 205]
  [228 216 205]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [230 216 208]
  [229 216 207]
  [228 216 206]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [231 215 209]
  [229 216 209]
  [229 216 208]]

 ...

 [[120 129 142]
  [119 129 143]
  [119 129

True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [236 215 216]
  [236 215 218]
  [236 214 219]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [236 216 216]
  [236 215 217]
  [236 214 218]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [236 216 215]
  [236 215 217]
  [236 215 218]]

 ...

 [[121 125 153]
  [122 126 152]
  [123 126 150]
  ...
  [112  97  78]
  [112  99  74]
  [113 101  73]]

 [[119 125 150]
  [120 126 149]
  [122 126 147]
  ...
  [116  95  77]
  [118  98  73]
  [118  99  71]]

 [[119 126 149]
  [120 126 148]
  [122 127 146]
  ...
  [119  94  77]
  [121  98  73]
  [122  99  70]]]
True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [236 215 216]
  [236 215 218]
  [236 214 219]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [236 216 216]
  [236 215 217]
  [236 214 218]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [236 216 215]
  [236 215 217]
  [236 215 218]]

 ...

 [[121 125 153]
  [122 126 152]
  [123 126

True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [232 215 216]
  [232 215 219]
  [232 214 220]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [231 215 216]
  [232 215 219]
  [232 214 220]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [231 215 216]
  [231 214 218]
  [232 214 220]]

 ...

 [[123 120 156]
  [122 120 156]
  [118 120 154]
  ...
  [ 25  26  24]
  [ 25  26  24]
  [ 25  26  24]]

 [[127 118 154]
  [126 119 154]
  [123 119 154]
  ...
  [ 24  24  24]
  [ 24  24  25]
  [ 24  24  25]]

 [[130 118 154]
  [129 118 154]
  [127 120 154]
  ...
  [ 24  24  25]
  [ 24  23  26]
  [ 24  23  26]]]
True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [232 215 216]
  [232 215 219]
  [232 214 220]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [231 215 216]
  [232 215 219]
  [232 214 220]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [231 215 216]
  [231 214 218]
  [232 214 220]]

 ...

 [[123 120 156]
  [122 120 156]
  [118 120

True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [232 214 214]
  [232 214 213]
  [232 215 213]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [232 214 214]
  [232 214 214]
  [232 214 214]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [232 214 215]
  [232 214 215]
  [232 214 215]]

 ...

 [[126 125 147]
  [125 124 147]
  [125 124 148]
  ...
  [ 21  22  43]
  [ 18  22  44]
  [ 16  22  44]]

 [[129 123 144]
  [129 123 145]
  [130 123 147]
  ...
  [ 19  19  45]
  [ 15  19  45]
  [ 12  18  44]]

 [[129 121 142]
  [130 122 143]
  [131 122 145]
  ...
  [ 18  19  47]
  [ 13  17  45]
  [ 10  15  44]]]
True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [232 214 214]
  [232 214 213]
  [232 215 213]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [232 214 214]
  [232 214 214]
  [232 214 214]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [232 214 215]
  [232 214 215]
  [232 214 215]]

 ...

 [[126 125 147]
  [125 124 147]
  [125 124

True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [230 215 213]
  [228 216 212]
  [227 215 210]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [230 215 213]
  [228 214 211]
  [228 215 211]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [230 213 213]
  [230 213 213]
  [230 213 213]]

 ...

 [[120 130 134]
  [120 129 134]
  [119 125 134]
  ...
  [ 44  41  52]
  [ 56  54  66]
  [ 66  65  78]]

 [[113 123 130]
  [114 122 131]
  [114 119 131]
  ...
  [ 42  38  54]
  [ 53  51  68]
  [ 63  61  79]]

 [[107 117 125]
  [108 116 126]
  [111 116 129]
  ...
  [ 39  34  53]
  [ 50  47  66]
  [ 60  58  78]]]
True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [230 215 213]
  [228 216 212]
  [227 215 210]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [230 215 213]
  [228 214 211]
  [228 215 211]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [230 213 213]
  [230 213 213]
  [230 213 213]]

 ...

 [[120 130 134]
  [120 129 134]
  [119 125

True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [240 212 202]
  [241 213 202]
  [240 213 202]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [239 212 205]
  [239 213 204]
  [240 214 205]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [238 212 209]
  [237 212 208]
  [238 214 209]]

 ...

 [[ 33  36  54]
  [ 34  36  53]
  [ 43  42  59]
  ...
  [ 27  21  36]
  [ 33  27  43]
  [ 39  32  49]]

 [[ 29  36  56]
  [ 33  38  58]
  [ 42  45  63]
  ...
  [ 28  19  38]
  [ 34  25  46]
  [ 42  32  55]]

 [[ 31  39  62]
  [ 33  40  62]
  [ 44  49  68]
  ...
  [ 27  18  39]
  [ 34  24  48]
  [ 42  31  57]]]
True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [240 212 202]
  [241 213 202]
  [240 213 202]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [239 212 205]
  [239 213 204]
  [240 214 205]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [238 212 209]
  [237 212 208]
  [238 214 209]]

 ...

 [[ 33  36  54]
  [ 34  36  53]
  [ 43  42

True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [232 217 217]
  [233 218 216]
  [233 218 216]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [234 217 217]
  [234 218 216]
  [234 218 216]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [237 218 219]
  [236 217 216]
  [236 218 215]]

 ...

 [[ 59  59  63]
  [ 59  59  63]
  [ 60  59  66]
  ...
  [119 110 116]
  [117 110 118]
  [122 115 125]]

 [[ 59  59  59]
  [ 60  59  61]
  [ 60  58  63]
  ...
  [112 106 110]
  [112 106 114]
  [115 110 119]]

 [[ 58  59  57]
  [ 59  59  59]
  [ 59  58  61]
  ...
  [113 107 111]
  [111 106 114]
  [111 107 117]]]
True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [232 217 217]
  [233 218 216]
  [233 218 216]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [234 217 217]
  [234 218 216]
  [234 218 216]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [237 218 219]
  [236 217 216]
  [236 218 215]]

 ...

 [[ 59  59  63]
  [ 59  59  63]
  [ 60  59

True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [234 215 217]
  [232 215 218]
  [232 215 218]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [233 215 217]
  [232 215 218]
  [232 215 218]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [232 216 217]
  [232 215 218]
  [232 215 218]]

 ...

 [[ 28  25  42]
  [ 25  23  39]
  [ 23  22  36]
  ...
  [ 29  27  33]
  [ 31  28  34]
  [ 32  29  35]]

 [[ 29  26  39]
  [ 26  24  36]
  [ 23  23  34]
  ...
  [ 28  27  34]
  [ 30  29  36]
  [ 31  29  37]]

 [[ 28  26  35]
  [ 26  25  34]
  [ 24  24  34]
  ...
  [ 27  26  35]
  [ 30  29  38]
  [ 31  30  39]]]
True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [234 215 217]
  [232 215 218]
  [232 215 218]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [233 215 217]
  [232 215 218]
  [232 215 218]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [232 216 217]
  [232 215 218]
  [232 215 218]]

 ...

 [[ 28  25  42]
  [ 25  23  39]
  [ 23  22

True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [230 213 216]
  [230 214 215]
  [231 215 216]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [230 214 215]
  [230 214 214]
  [230 214 214]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [230 214 214]
  [230 215 213]
  [230 215 212]]

 ...

 [[ 45  44  60]
  [ 42  41  56]
  [ 38  38  51]
  ...
  [ 73  68  56]
  [ 69  67  56]
  [ 66  66  55]]

 [[ 48  44  60]
  [ 43  39  54]
  [ 37  33  48]
  ...
  [ 70  69  52]
  [ 66  68  52]
  [ 63  67  52]]

 [[ 50  44  59]
  [ 43  37  52]
  [ 36  29  46]
  ...
  [ 69  70  50]
  [ 65  69  51]
  [ 63  68  51]]]
True
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [230 213 216]
  [230 214 215]
  [231 215 216]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [230 214 215]
  [230 214 214]
  [230 214 214]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [230 214 214]
  [230 215 213]
  [230 215 212]]

 ...

 [[ 45  44  60]
  [ 42  41  56]
  [ 38  38